### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Coding-Hashira**
Committing myself to the dojo way! ⚡

Super happy and excited to join! 🥳

_Drank Blood of a Unicorn at the Silicon Valley! 🦄_

### CODE REVIEW

**Review by kalyan-vurugonda — CHANGES_REQUESTED** [review]
Hi @Coding-Hashira,
Your contribution is good.
It is better to write a link in the above format like https://twitter.com/coding_hashira. It is a good way to represent. 
Make the changes and make a PR again.

**Comment by Coding-Hashira** [comment]
@kalyan-vurugonda Just realised it, thanks for telling, mate! 😅

**Comment by Coding-Hashira** [comment]
> Hi @Coding-Hashira,
> Your contribution is good.
> It is better to write a link in the above format like https://twitter.com/coding_hashira. It is a good way to represent. 
> Make the changes and make a PR again.

Just fixed it and added the commit, mate! 😁

**Comment by kalyan-vurugonda** [comment]
> > Hi @Coding-Hashira,
> > Your contribution is good.
> > It is better to write a link in the above format like https://twitter.com/coding_hashira. It is a good way to represent.
> > Make the changes and make a PR again.
> 
> Just fixed it and added the commit, mate! 😁

Okay, Looks Good!

**Pull request merged**
