### PR TITLE
shivam005-stack-patch-1

### PR DESCRIPTION
**Pull request by shivam005-stack**
- [Jasmine Vo](https://twitter.com/jasminepvodev)
- [John Green](https://twitter.com/JohnGreenDev)	
- [Fumudukus](https://twitter.com/OnyelaUdochukw1)	
- [Adetoye](https://twitter.com/adetoye_dev)
- [Olamide Farouq](https://twitter.com/Olamide_farouq)	
- [Shivam Durani](https://twitter.com/Shivam44694351)

### CODE REVIEW

**Comment by ykdojo** [comment]
Please change the file

**Comment by shivam005-stack** [comment]
What Changes Do I Have ?
Can U Please Help

**Comment by maxdemaio** [comment]
@shivam005-stack In your forked repository, make the changes you want to your `README.md` file. After, commit the changes and open a pull request against this repository 😃

**Comment by shivam005-stack** [comment]
Thanks For The Help :)

@maxdemaio

**Pull request closed without merging**
